CREATE TABLE IF NOT EXISTS market_index_cursor (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  chain VARCHAR(32) NOT NULL,
  source_kind VARCHAR(32) NOT NULL DEFAULT 'aggregate',
  source_label VARCHAR(80) NOT NULL DEFAULT 'Market Events',
  source_address VARCHAR(80) NOT NULL DEFAULT '',
  from_block BIGINT UNSIGNED NULL,
  to_block BIGINT UNSIGNED NULL,
  target_block BIGINT UNSIGNED NULL,
  is_indexing TINYINT(1) NOT NULL DEFAULT 0,
  flashloan_rows INT UNSIGNED NOT NULL DEFAULT 0,
  liquidation_rows INT UNSIGNED NOT NULL DEFAULT 0,
  last_started_at DATETIME NULL,
  last_completed_at DATETIME NULL,
  last_error TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_market_index_cursor (chain, source_kind, source_address),
  KEY idx_market_index_cursor_chain (chain),
  KEY idx_market_index_cursor_indexing (is_indexing)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS market_flashloan_events (
  event_id CHAR(64) NOT NULL,
  chain VARCHAR(32) NOT NULL,
  protocol VARCHAR(80) NOT NULL,
  purpose VARCHAR(80) NOT NULL,
  block_number BIGINT UNSIGNED NOT NULL,
  event_time INT UNSIGNED NOT NULL,
  tx_hash VARCHAR(80) NOT NULL,
  borrower VARCHAR(80) NOT NULL,
  asset VARCHAR(128) NOT NULL,
  amount_usd DECIMAL(38, 12) NOT NULL DEFAULT 0,
  fee_usd DECIMAL(38, 12) NOT NULL DEFAULT 0,
  token_count INT UNSIGNED NOT NULL DEFAULT 0,
  lp_count INT UNSIGNED NOT NULL DEFAULT 0,
  legs_json JSON NULL,
  raw_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (event_id),
  KEY idx_market_flashloan_chain_time (chain, event_time),
  KEY idx_market_flashloan_chain_block (chain, block_number),
  KEY idx_market_flashloan_protocol_time (protocol, event_time),
  KEY idx_market_flashloan_asset_time (asset, event_time),
  KEY idx_market_flashloan_borrower_time (borrower, event_time),
  KEY idx_market_flashloan_tx (tx_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS market_liquidation_events (
  event_id CHAR(64) NOT NULL,
  chain VARCHAR(32) NOT NULL,
  protocol VARCHAR(80) NOT NULL,
  block_number BIGINT UNSIGNED NOT NULL,
  event_time INT UNSIGNED NOT NULL,
  tx_hash VARCHAR(80) NOT NULL,
  borrower VARCHAR(80) NOT NULL,
  liquidator VARCHAR(80) NOT NULL,
  debt_asset VARCHAR(128) NOT NULL,
  debt_to_cover_usd DECIMAL(38, 12) NOT NULL DEFAULT 0,
  debt_quantity DECIMAL(38, 12) NOT NULL DEFAULT 0,
  liquidation_asset VARCHAR(128) NOT NULL,
  liquidation_amount_usd DECIMAL(38, 12) NOT NULL DEFAULT 0,
  liquidation_quantity DECIMAL(38, 12) NOT NULL DEFAULT 0,
  profit_usd DECIMAL(38, 12) NOT NULL DEFAULT 0,
  raw_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (event_id),
  KEY idx_market_liquidation_chain_time (chain, event_time),
  KEY idx_market_liquidation_chain_block (chain, block_number),
  KEY idx_market_liquidation_protocol_time (protocol, event_time),
  KEY idx_market_liquidation_liquidator_time (liquidator, event_time),
  KEY idx_market_liquidation_borrower_time (borrower, event_time),
  KEY idx_market_liquidation_asset_time (liquidation_asset, event_time),
  KEY idx_market_liquidation_tx (tx_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS market_index_runs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  chain VARCHAR(32) NOT NULL,
  period VARCHAR(16) NOT NULL,
  from_block BIGINT UNSIGNED NULL,
  to_block BIGINT UNSIGNED NULL,
  flashloan_rows INT UNSIGNED NOT NULL DEFAULT 0,
  liquidation_rows INT UNSIGNED NOT NULL DEFAULT 0,
  started_at DATETIME NOT NULL,
  completed_at DATETIME NULL,
  ok TINYINT(1) NOT NULL DEFAULT 0,
  error TEXT NULL,
  PRIMARY KEY (id),
  KEY idx_market_index_runs_chain_started (chain, started_at),
  KEY idx_market_index_runs_ok (ok)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS market_hourly_stats (
  stat_id CHAR(64) NOT NULL,
  chain VARCHAR(32) NOT NULL,
  event_type VARCHAR(32) NOT NULL,
  protocol VARCHAR(80) NOT NULL,
  bucket_start INT UNSIGNED NOT NULL,
  tx_count INT UNSIGNED NOT NULL DEFAULT 0,
  amount_usd DECIMAL(38, 12) NOT NULL DEFAULT 0,
  fee_usd DECIMAL(38, 12) NOT NULL DEFAULT 0,
  profit_usd DECIMAL(38, 12) NOT NULL DEFAULT 0,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (stat_id),
  UNIQUE KEY uniq_market_hourly_stats (chain, event_type, protocol, bucket_start),
  KEY idx_market_hourly_chain_bucket (chain, bucket_start),
  KEY idx_market_hourly_event_bucket (event_type, bucket_start)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
