export const DASHBOARD_STATE_LOGIC = String.raw`
      const DEFAULT_ARBITRAGE_TOKEN_LIST = 'BTC, ETH, SOL, BNB';
      const ARBITRAGE_TOKEN_STORAGE_KEY = 'dashboard-arbitrage-token';

      const state = {
        language: localStorage.getItem('dashboard-language') || 'en',
        page: localStorage.getItem('dashboard-page') || 'overview',
        settingsSection: localStorage.getItem('dashboard-settings-section') || 'general',
        overviewPeriod: localStorage.getItem('dashboard-overview-period') || '7',
        flashloanPeriod: localStorage.getItem('dashboard-flashloan-period') || '7',
        leaderboardTab: localStorage.getItem('dashboard-leaderboard-tab') || 'txProfit',
        morphoOpportunityView: localStorage.getItem('dashboard-morpho-opportunity-view') || 'all',
        morphoChain: localStorage.getItem('dashboard-morpho-chain') || 'ethereum',
        morphoOverviewRefreshing: false,
        morphoExecutorChecking: false,
        bootLoading: true,
        data: {
          config: null,
          version: null,
          liveState: null,
          history: null,
          wallet: null,
          settings: null,
          marketDataIndexStatus: null,
          quicknodeUsage: null,
          rpcUsage: null,
          publicLiquidationFeed: null,
          liquidationQueue: null,
          strategy: null,
          morphoBlueMarkets: null,
          morphoBlueBaseMarkets: null,
          eigenphiOverview: null,
          eigenphiLeaderboard: null,
          eigenphiLatestLiquidation: null,
          eigenphiFlashloanOverview: null
        },
	        loading: {
	          morphoBlueMarkets: true,
	          morphoBlueBaseMarkets: true,
	          eigenphiOverview: true,
	          eigenphiLeaderboard: true,
	          eigenphiLatestLiquidation: true,
	          eigenphiFlashloanOverview: true,
	          walletAssets: false
	        },
        latestLiquidation: {
          date: '',
          unit: localStorage.getItem('dashboard-latest-liquidation-unit') || 'usd',
          page: 0,
          pageSize: Number(localStorage.getItem('dashboard-latest-liquidation-page-size') || '10') || 10,
          pickerOpen: false,
          pickerYear: null,
          pickerMonth: null,
          cache: {},
          inflight: {},
          requestId: 0
        },
        flashloanLatest: {
          page: 0,
          pageSize: Number(localStorage.getItem('dashboard-flashloan-page-size') || '10') || 10
        },
        flashloanDeskFilter: 'all',
        lab: null,
        form: {
          market: 'aave-v3-ethereum',
          chain: 'ethereum',
          lookbackBlocks: '2000',
          limit: '50',
          morphoMarketId: '',
          morphoKind: '',
          minNetProfit: '',
          rpcUrl: '',
          addressProvider: '',
          debtFilter: '',
          collateralFilter: '',
          hfMax: '1.05',
          datasetMode: 'merged',
          user: '',
          contract: '',
          allowRisky: false,
          autoSwap: true,
          broadcast: true,
          distributeProfit: false,
          deploy: false,
          liquidationOnly: true
        },
        running: false,
        hasConsoleRun: false,
        hasHydratedForm: false,
        runStateMode: 'idle',
        terminal: '$ workstation ready',
        consoleLiveTargets: [],
        consoleFilter: 'all',
        consoleSourceFilter: 'all',
        morphoMarketSort: 'liquidatable',
        arbitrageFilter: 'all',
        consoleStreamMode: false,
        arbitrageRunning: false,
        arbitrageHasRun: false,
        arbitrageRunStateMode: 'idle',
        arbitrageTerminal: '$ CEX arbitrage workspace ready\n$ 修改配置里的交易所和币对后启动扫描',
        arbitrageLiveTargets: [],
        arbitrageAutoExecuteAbortController: null,
        arbitrageAutoExecuteResumeCursor: null,
        arbitrageAutoExecuteSelection: null,
        arbitrageAutoExecuteRunSerial: 0,
        arbitrageLastResult: null,
        arbitragePendingRestart: false,
        arbitrageForm: {
          market: 'route-arb-ethereum',
          venues: 'binance,okx,bitget,mexc,gate',
          chain: 'cex',
          lookbackBlocks: '',
          limit: '',
          minNetProfit: '',
          rpcUrl: '',
          token: readStoredArbitrageToken() || DEFAULT_ARBITRAGE_TOKEN_LIST,
          hfMax: '',
          allowRisky: false,
          autoSwap: false,
          broadcast: false
        },
        autoExecuteAbortController: null,
        autoExecuteResumeCursor: null,
        autoExecuteSelection: null,
        autoExecuteRunSerial: 0,
        morphoReadOnlyRunning: false,
        selectedTarget: null,
        lastResult: null,
        charts: {
          trend: null,
          distribution: null,
          modalTrend: null,
          modalDistribution: null
        },
        settingsMasked: true,
        settingsDirty: false,
        settingsEditing: false,
        settingsRawValues: {},
        txGraph: {
          hash: '',
          chain: 'ethereum',
          rpcUrl: '',
          showTransfers: true,
          showCalls: true,
          showReferences: true,
          loading: false,
          data: null,
          cy: null,
          layout: null,
          dragPulseTimer: null,
          manualPositions: {},
          selectedNodeId: '',
          selectedEdgeId: '',
          graphKey: '',
          renderKey: '',
          overviewMode: false
        }
      };

      const validPages = ['overview', 'flashloan', 'liquidation', 'morpho', 'console', 'flashloanConsole', 'lab', 'arbitrage', 'txgraph', 'strategyPlaza', 'settings'];

      const SENSITIVE_SETTINGS_FIELD_IDS = [
        'settingsPrivateKey',
        'settingsBitqueryApiKey',
        'settingsZeroExApiKey',
        'settingsQuickNodeApiKey',
        'settingsControlRpc',
        'settingsExecutionRpc',
        'settingsFlashbotsRelay',
        'settingsFlashbotsAuth',
        'settingsEthereumRpc',
        'settingsBaseRpc',
        'settingsEthereumContract',
        'settingsSparkContract',
        'settingsPolygonRpc',
        'settingsPolygonContract',
        'settingsArbitrumRpc',
        'settingsArbitrumContract',
        'settingsBnbRpc',
        'settingsBnbContract',
        'settingsBinanceApiKey',
        'settingsBinanceSecretKey',
        'settingsOkxApiKey',
        'settingsOkxSecretKey',
        'settingsBitgetApiKey',
        'settingsBitgetSecretKey',
        'settingsMexcApiKey',
        'settingsMexcSecretKey',
        'settingsGateApiKey',
        'settingsGateSecretKey'
      ];
`;
